CREATE TABLE sounds (
    id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    name VARCHAR(64) NOT NULL,
    extension VARCHAR(32) NOT NULL,
    data MEDIUMBLOB NOT NULL,
    mime VARCHAR(64) NOT NULL,
    uploader INT NOT NULL,
    uploaded DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

